const GROUP1 = [
    'Softwareentwickler,in',
    'Projektmanager,in',
    'Informatiker,in',
    'Student,in (Betriebswirtschaftslehre)',
    'Ingenieur,in des Maschinen-, Apparate- und Fahrzeugtechnik',
    'IT-Consultant',
    'Unternehmensberater,in',
    'Kaufmann,frau Einzelhandel (kein Lebensmittelein)',
    'Kaufmann,frau Büro',
    'Kaufmann,frau (sonstige)',
    'Auszubildende,r (Bankkaufmann,-kauffrau)',
    'Softwareingenieur,in',
    'Diplom-Kaufmann,frau',
    'Auszubildende,r (Kaufmann,Kauffrau für Büromanagement)',
    'Auszubildende,r (Kaufmann,Kauffrau im Groß- und Außenhandel)',
    'Auszubildende,r (Kaufmann,Kauffrau im Einzelhandel)',
    'Kaufmann,frau (EDV)',
    'IT-System-Kaufmann,-frau',
    'Auszubildende,r (Kaufmann,Kauffrau für Spedition und Logistikdienstleistung)',
    'Sparkassenkaufmann,frau',
    'Vertriebskaufmann,frau',
    'Kaufmann,frau Versicherung',
    'Kaufmann,frau Industrie',
    'Personalfachkaufmann,frau',
    'Kaufmann,frau Spedition',
    'Industriekaufmann,frau',
    'Bürokaufmann,frau',
    'Bankkaufmann,frau',
    'Schüler,in',
    'Kaufmännische,r Angestellte,r (sonstige)',
    'IT-Berater,in',
    'Produktmanager,in',
    'Speditionskaufmann,frau',
    'Versicherungskaufmann,frau',
    'Einzelhandelskaufmann,frau (kein Lebensmitteleinzelhandel)',
    'Einzelhandelskaufmann,frau (Lebensmitteleinzelhandel)',
    'Verwaltungsfachangestellte,r',
    'Dozent,in',
    'Kaufmann,frau Bürokommunikation',
    'Groß- und Außenhandelskaufmann, frau',
    'Assistenzarzt,ärztin',
    'Steuerfachangestellte,r',
    'Vertriebsleiter,in',
    'Automobilkaufmann,frau',
    'Zahnarzt,ärztin',
    'Student,in (Wirtschaftsinformatik)',
    'Hotelfachmann,frau',
    'Sekretär,in',
    'Teamsekretär,in',
    'Student,in (Informatik)',
    'Sozialversicherungsangestellte,r',
    'Immobilienkaufmann,frau',
    'Geschäftsführer,in (sonstige)',
    'Bürofachkraft, Kaufmännische,r Angestellte',
    'Assistent,in der Geschäftsleitung',
    'Bauzeichner,in',
    'Personalberater,in',
    'Kaufmännisch-technische,r Angestellte,r',
    'Immobilienmakler,in',
    'Geologe,Geologin',
    'Auszubildende,r (Industriekaufmann,-kauffrau)',
    'Auszubildende,r (Hotelfachmann,-fachfrau)',
    'Sozialversicherungsfachangestellte,r',
    'Technische,r Zeichner,in',
    'Touristikkaufmann,frau',
    'Zahnmedizinische,r Assistent,in',
    'Sport und Fitnesskaufmann,frau',
    'Anwendungsprogrammierer,in',
    'Student,in (Medizintechnik)',
    'Hotelkaufmann,frau',
    'Zahnmedizinische,r Fachhelfer,in',
    'Auszubildende,r (Sozialversicherungsfachangestellte,r)',
    'Gesellschafter,in Geschäftsführer,in',
    'Fremdsprachenkorrespondent,in',
    'Zahnmedizinisch-technische,r Assistent,in',
    'Tierarzthelfer,in',
    'Marketingkaufmann,frau',
    'Tierarzt,ärztin',
    'Finanzberater,in',
    'Krankenpflegehelferschüler,in',
    'Chefsekretär,in',
    'Justizvollzugsobersekretär,in',
    'Reisebürokaufmann,frau',
    'Makler,in',
    'Handwerksmeister,in',
    'Sekretär,in Gesundheitswesen',
    'Reiseverkehrskaufmann,frau',
    'Sekretär,in Fremdsprachen staatlich geprüft',
    'Vertriebsleiter,in (EDV)',
    'Diplom-Geologe,Geologin',
    'Hotelier,in',
    'Diplom-Agraringenieur,in',
    'Empfangssekretär,in',
    'Regierungssekretär,in',
    'Dozent,in (EDV)',
    'Fremdsprachensekretär,in',
    'Datenverarbeitungskaufmann,frau',
    'Flugzeugwartungsingenieur,in',
    'Kaufmännische,r Geschäftsführer,in',
    'Justizsekretär,in',
    'Technische,r Geschäftsführer,in',
    'Geophysiker,in',
    'Agrarwissenschaftler,in',
    'Justizangestellte,r',
    'Auszubildende,r (Verwaltungsfachangestellte,r)',
    'Unternehmer,in, Geschäftsführer,in',
    'Hochschullehrer,in',
    'Berufsberater,in',
    'Kaufmännische,r Assistent,in Gesundheitswesen',
    'Augenoptiker,in',
    'Marketingsekretär,in',
    'Justizsekretäranwärter,in',
];

const GROUP2 = ['Softwareentwickler,in'];
module.exports = { GROUP1, GROUP2 };